In [ ]:
!wget --no-cache -O init.py -q https://raw.githubusercontent.com/UDEA-Esp-Analitica-y-Ciencia-de-Datos/EACD-01-FUNDAMENTOS/master/init.py
import init; init.init(force_download=False);

# Ejemplos Pandas

Ahora unos ejemplos usando Pandas y un [dataset the Pokemon](https://github.com/travishn/pokemon-showdown-scraper/tree/master/pokemon-data).

In [1]:
import pandas as pd

Leer un CSV es bastante f√°cil usando Pandas

In [43]:
df_gen1 = pd.read_csv("local/data/pokemon-gen1-data.csv")
df_gen2 = pd.read_csv("local/data/pokemon-gen2-data.csv")

Ahora podemos crear unas breves descripciones de los datos...

In [44]:
df_gen1.head()

,Pokemon,Number,Type1,Type2,Ability1,Ability2,Ability3,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Sprite
0,Bulbasaur,1,GRASS,POISON,Overgrow,Chlorophyll,none,45,49,49,65,65,45,https://play.pokemonshowdown.com/sprites/bw/bu...
1,Ivysaur,2,GRASS,POISON,Overgrow,Chlorophyll,none,60,62,63,80,80,60,https://play.pokemonshowdown.com/sprites/bw/iv...
2,Venusaur,3,GRASS,POISON,Overgrow,Chlorophyll,none,80,82,83,100,100,80,https://play.pokemonshowdown.com/sprites/bw/ve...
3,Charmander,4,FIRE,none,Blaze,Solar Power,none,39,52,43,60,50,65,https://play.pokemonshowdown.com/sprites/bw/ch...
4,Charmeleon,5,FIRE,none,Blaze,Solar Power,none,58,64,58,80,65,80,https://play.pokemonshowdown.com/sprites/bw/ch...

In [45]:
df_gen2.head()

,Pokemon,Number,Type1,Type2,Ability1,Ability2,Ability3,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Sprite
0,Chikorita,152,GRASS,none,Overgrow,Leaf Guard,none,45,49,65,49,65,45,https://play.pokemonshowdown.com/sprites/bw/ch...
1,Bayleef,153,GRASS,none,Overgrow,Leaf Guard,none,60,62,80,63,80,60,https://play.pokemonshowdown.com/sprites/bw/ba...
2,Meganium,154,GRASS,none,Overgrow,Leaf Guard,none,80,82,100,83,100,80,https://play.pokemonshowdown.com/sprites/bw/me...
3,Cyndaquil,155,FIRE,none,Blaze,Flash Fire,none,39,52,43,60,50,65,https://play.pokemonshowdown.com/sprites/bw/cy...
4,Quilava,156,FIRE,none,Blaze,Flash Fire,none,58,64,58,80,65,80,https://play.pokemonshowdown.com/sprites/bw/qu...

podemos combinar ambos datasets en uno solo, para manejarlo m√°s f√°cilmente

In [49]:
df = pd.concat([df_gen1, df_gen2], keys=["gen1", "gen2"])

In [50]:
df

            Pokemon  Number    Type1   Type2      Ability1     Ability2  \
gen1 0    Bulbasaur       1    GRASS  POISON      Overgrow  Chlorophyll
     1      Ivysaur       2    GRASS  POISON      Overgrow  Chlorophyll
     2     Venusaur       3    GRASS  POISON      Overgrow  Chlorophyll
     3   Charmander       4     FIRE    none         Blaze  Solar Power
     4   Charmeleon       5     FIRE    none         Blaze  Solar Power
...             ...     ...      ...     ...           ...          ...
gen2 95     Pupitar     247     ROCK  GROUND     Shed Skin         none
     96   Tyranitar     248     ROCK    DARK   Sand Stream      Unnerve
     97       Lugia     249  PSYCHIC  FLYING      Pressure   Multiscale
     98       Ho-Oh     250     FIRE  FLYING      Pressure  Regenerator
     99      Celebi     251  PSYCHIC   GRASS  Natural Cure         none

        Ability3   HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
gen1 0      none   45      49       49       65       65     45
     1      none   60      62       63       80       80     60
     2      none   80      82       83      100      100     80
     3      none   39      52       43       60       50     65
     4      none   58      64       58       80       65     80
...          ...  ...     ...      ...      ...      ...    ...
gen2 95     none   70      84       70       65       70     51
     96     none  100     134      110       95      100     61
     97     none  106      90      130       90      154    110
     98     none  106     130       90      110      154     90
     99     none  100     100      100      100      100    100

                                                    Sprite
gen1 0   https://play.pokemonshowdown.com/sprites/bw/bu...
     1   https://play.pokemonshowdown.com/sprites/bw/iv...
     2   https://play.pokemonshowdown.com/sprites/bw/ve...
     3   https://play.pokemonshowdown.com/sprites/bw/ch...
     4   https://play.pokemonshowdown.com/sprites/bw/ch...
...                                                    ...
gen2 95  https://play.pokemonshowdown.com/sprites/bw/pu...
     96  https://play.pokemonshowdown.com/sprites/bw/ty...
     97  https://play.pokemonshowdown.com/sprites/bw/lu...
     98  https://play.pokemonshowdown.com/sprites/bw/ho...
     99  https://play.pokemonshowdown.com/sprites/bw/ce...

[251 rows x 14 columns]

Honestamente, a m√≠ me parece un poco m√°s enredado trabajar con m√∫ltiples √≠ndices, por lo que convertir√© los datos a un dataframe con un solo √≠ndice

In [54]:
df = df.reset_index(level=0).rename(columns={"level_0": "generation"}).reset_index().drop(columns="index")
df.head()

,generation,Pokemon,Number,Type1,Type2,Ability1,Ability2,Ability3,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Sprite
0,gen1,Bulbasaur,1,GRASS,POISON,Overgrow,Chlorophyll,none,45,49,49,65,65,45,https://play.pokemonshowdown.com/sprites/bw/bu...
1,gen1,Ivysaur,2,GRASS,POISON,Overgrow,Chlorophyll,none,60,62,63,80,80,60,https://play.pokemonshowdown.com/sprites/bw/iv...
2,gen1,Venusaur,3,GRASS,POISON,Overgrow,Chlorophyll,none,80,82,83,100,100,80,https://play.pokemonshowdown.com/sprites/bw/ve...
3,gen1,Charmander,4,FIRE,none,Blaze,Solar Power,none,39,52,43,60,50,65,https://play.pokemonshowdown.com/sprites/bw/ch...
4,gen1,Charmeleon,5,FIRE,none,Blaze,Solar Power,none,58,64,58,80,65,80,https://play.pokemonshowdown.com/sprites/bw/ch...

podemos sacar un breve resumen de nuestro dataset

In [58]:
df.describe()

,Number,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
count,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000
mean,126.000000,66.908367,71.059761,68.808765,66.087649,68.577689,66.015936
std,72.601653,29.794153,27.469117,30.442524,27.373277,27.480556,27.316510
min,1.000000,10.000000,5.000000,5.000000,10.000000,20.000000,5.000000
25%,63.500000,49.000000,50.000000,49.500000,45.000000,50.000000,45.000000
50%,126.000000,65.000000,70.000000,65.000000,65.000000,65.000000,65.000000
75%,188.500000,80.000000,90.000000,85.000000,85.000000,85.000000,85.000000
max,251.000000,255.000000,134.000000,230.000000,154.000000,230.000000,150.000000

A partir de este punto puedes empezar a utilizar pandas para responder las preguntas que acerca de tus datos.

**¬øCu√°ntos Pokemon hay en cada generaci√≥n?***

In [76]:
df.groupby("generation").size()

generation
gen1    151
gen2    100
dtype: int64

**¬øCu√°les son los tipos de Pokemon con mayor velocidad promedio?**

In [75]:
df.groupby("Type1").mean()["Speed"]

Type1
BUG         54.545455
DARK        86.200000
DRAGON      66.666667
ELECTRIC    87.000000
FAIRY       35.000000
FIGHTING    63.111111
FIRE        78.800000
GHOST       92.500000
GRASS       55.238095
GROUND      58.181818
ICE         70.000000
NORMAL      66.621622
POISON      63.533333
PSYCHIC     87.333333
ROCK        54.461538
STEEL       50.000000
WATER       63.456522
Name: Speed, dtype: float64

In [88]:
df[["generation", "HP", "Attack", "Defense", "Sp. Atk", "Sp. Def", "Speed"]].groupby("generation").mean()

                   HP     Attack    Defense    Sp. Atk    Sp. Def      Speed
generation
gen1        64.211921  72.913907  68.225166  67.139073  66.086093  69.066225
gen2        70.980000  68.260000  69.690000  64.500000  72.340000  61.410000